stages:
  - test
test:
  stage: test
  image: node:18
  script:
    - npm install
    - npx playwright install --with-deps
    - npx playwright test --grep @UI
    - npx playwright test --grep @API
    - npx playwright test --grep @E2E
