stages:
  - test
tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  parallel:
    matrix:
      - PROJECT: ['Chromium']
  script:
    - npm ci
    - npm run uitests --project=$PROJECT
    - npm run apitests --project=$PROJECT
    - npm run e2etests --project=$PROJECT