stages:
  - test
test:
  stage: test
  image: node:18  # Choose a Node.js version that suits your project
  script:
    - npm install
    - npx playwright install
    - npx playwright test --grep @API
