stages:
  - test
tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  parallel:
    matrix:
      - PROJECT: ['Chromium']
  script:
    - npm run regressiontests --project=$PROJECT
